# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MyMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'Kingfisher', '~> 7.0'

  pod 'FirebaseAuth'

  # Pods for MyMovies


end
